name: secret manager aws

on:
  workflow_dispatch:  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.5.0"  # Specify the Terraform version you want to use

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: "us-east-1"

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform plan
      run: terraform apply -auto-approve

    - name: Clean up Terraform state
      run: terraform destroy -auto-approve
