name: Modules

on:
  push:
    branches: LAB-2
  workflow_dispatch:
   
    

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image to run the Terraform commands

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'  # Set your required Terraform version

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1  # Set your AWS region

    - name: Terraform Init
      run: |
        terraform init -backend-config="key=vpc/terraform.tfstate" -backend-config="bucket=powertool1107" -backend-config="region=us-east-1" -backend-config="encrypt=true" -backend-config="versioning=true" -backend-config="dynamodb_table=powertool"
        terraform init -backend-config="key=security_group/terraform.tfstate" -backend-config="bucket=powertool1107" -backend-config="region=us-east-1" -backend-config="encrypt=true" -backend-config="versioning=true" -backend-config="dynamodb_table=powertool"
        terraform init -backend-config="key=subnet/terraform.tfstate" -backend-config="bucket="powertool1107" -backend-config="region=us-east-1" -backend-config="encrypt=true" -backend-config="versioning=true" -backend-config="dynamodb_table=powertool"
                      

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve tfplan

    - name: Capture Terraform Outputs
      run: |
        terraform output -json
